# Generated by Django 4.2.2 on 2023-07-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='Nombre de esta ciudad de destino turístico', max_length=50, unique=True)),
                ('descripcion', models.TextField(help_text='Descripción de esta ciudad de destino turístico')),
                ('imagen', models.ImageField(help_text='Imagen de esta ciudad de destino turístico', upload_to='static/images/')),
                ('precioTour', models.FloatField(help_text='Precio del tour a esta ciudad de destino turístico')),
                ('oferta', models.BooleanField(default=False, help_text='Decide si el viaje a este destino turístico está de oferta')),
            ],
        ),
    ]
