# Generated by Django 4.2.2 on 2023-07-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(help_text='Imagen de esta ciudad de destino turístico', upload_to='destinos'),
        ),
    ]
