# Generated by Django 4.2.2 on 2023-07-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0002_alter_destino_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='oferta',
            field=models.BooleanField(blank=True, default=False, help_text='Decide si el viaje a este destino turístico está de oferta'),
        ),
    ]
