# Generated by Django 4.2.2 on 2023-07-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0003_alter_destino_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='descuento',
            field=models.FloatField(blank=True, default=0, help_text='Descuento establecido por oferta (number | percentage)', null=True),
        ),
    ]
