# Generated by Django 4.2.2 on 2023-07-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0004_destino_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='tipoDescuento',
            field=models.CharField(blank=True, choices=[('#', 'number'), ('%', 'percentage')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='destino',
            name='descuento',
            field=models.FloatField(blank=True, default=0, help_text='Descuento establecido por oferta (number | percentage)'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='oferta',
            field=models.BooleanField(default=False, help_text='Decide si el viaje a este destino turístico está de oferta'),
        ),
    ]
